### ISSUE TITLE
macOS with external displays

### ISSUE THREAD

**Issue by dprestegard** [WICG/hdcp-detection#14]
Hello!

First off, this is awesome, and super useful. Thank you for making it!

I've noticed that on macOS the behavior is a bit unexpected. It seems to work normally when using the internal display on a macbook. I can see that HDCP is available, and in fact using all variants (which is kind of unexpected, but okay).

When I connect to a known HDCP compliant display it immediately says output-restricted. This is interesting because the FairPlay DRM in Safari can output to this display while enforcing HDCP no problem. I've tested it extensively. This leads me to believe that HDCP is in fact engaged, but the system is lying to Chrome :)

Why does Chrome get a different response back from macOS? This works totally fine on Windows.

**Comment by joeyparrish** [comment]
This repo is for the incubation of this extension to the W3C spec.  If you have an issue with the implementation in Chrome, please file a bug at https://crbug.com/ and the Chrome team can take a look.  Thanks!

**Comment by dprestegard** [comment]
Thanks! Sorry for the noise :)

**Comment by joeyparrish** [comment]
No worries!  Just wanted to help get you to the right place.

**Comment by OrenMe** [comment]
@dprestegard Could you please share the CR bug here, would like to track it. Thanks!

**Comment by dprestegard** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1083475&q=hdcp&can=2

**Comment by OrenMe** [comment]
Thanks!
