### ISSUE TITLE
Define HDCP version strings used for minHdcpVersion

### ISSUE THREAD

**Issue by xhwang-chromium** [WICG/hdcp-detection#8]
For better interoperability, we should define HDCP version strings (or string format) used for minHdcpVersion. For example, [these](https://cs.chromium.org/chromium/src/media/blink/webcontentdecryptionmodule_impl.cc) are currently used by Chromium:

- "hdcp-1.0"
- "hdcp-1.1"
- "hdcp-1.2"
- "hdcp-1.3"
- "hdcp-1.4"
- "hdcp-2.0"
- "hdcp-2.1"
- "hdcp-2.2"
- "hdcp-2.3"

**Comment by mounirlamouri** [comment]
Can we drop "hdcp-", it's simpler :)

**Comment by xhwang-chromium** [comment]
HDCP was there because somehow I was thinking about generalizing this to include other output protection mechanisms, e.g. CGMS. But that could be a different policy to check. Given it's minHdcpVersion, I agree we can drop the "hdcp-" part.

mounirlamouri: If you make a change to the explainer to include these strings (w/o "hdcp-"), I can update Chromium's implementation.

**Comment by mounirlamouri** [comment]
I've sent a PR in #9

**Comment by joeyparrish** [comment]
Fixed in #9
